
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yurgenwk/demo-server-hb:{{ .Values.app.version | default "latest"}}
        env:
        - name: MQ_URL
          value: {{ .Values.app.env.rabbitmq }}
---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 3000
      nodePort: 30080

  type: NodePort