username: ENC[AES256_GCM,data:0V5O13nAciOo,iv:/9duGftK1mO9ui3992bZFFOiW5+z4uhJ6KK3zDLM+eU=,tag:3bqzXlZTKQGzHslskkGWsA==,type:str]
password: ENC[AES256_GCM,data:BxcuyETt2/YVN2O0mQ==,iv:ZR5ALN90hTTWe8jzYLA0oLV+oHMwfRnvfT2Fg9lSlMA=,tag:z9BUZP9Xqrbwg/eXazdUYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-05-22T13:50:00Z'
    mac: ENC[AES256_GCM,data:DqKuENd1p6ndc3OSAb2hunHpmvZtCyE6HAqyxHkd69llmm1LNe0pQdctMxMkRYCzAqp2n7n79TY8o4wvaWSYZnnHR9ufWGAINh9DpSxxW/vBHc/6Mfo10QOrmtt+UD56eeNbpTjEzZMdkkpJAn1dV+g4VHf4oBSx1KKMKFNAM98=,iv:rZi1k+nyNsS7/X/m99O1AzPfAN4OGET0kG/2+3yI0Yc=,tag:I0wUctQ5iBfbjA3OkE6hgQ==,type:str]
    pgp:
    -   created_at: '2022-05-22T13:50:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DUgjdIe8ZMigSAQdAaFWpw5jt5xAsHLkai7rtIoO9N43n68eEG7tmtbrZMzcw
            7eQ4wxoTfg1OlXjxCCO/k1TEG8YZU/eo0kNXoj62n0PJNseM0WvOKER0tbyIEsec
            0l4BsatDK7AP66QdQthNqMkTLoZBO9tfmGdRQL0/niEJID3y4SbqS4dX+CpmJSho
            WJOarzC6tS0iXNWQwP9/POur7dyVq3W8QWMTQLYL1nXg03RYIBRQ4qdxhQswqwwF
            =L0gG
            -----END PGP MESSAGE-----
        fp: 88D3C0D03895A07DB04A393FE6C332F04B58CA6A
    unencrypted_suffix: _unencrypted
    version: 3.5.0
