# permissions for end users to edit memoryadjusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-project
    app.kubernetes.io/managed-by: kustomize
  name: memoryadjuster-editor-role
rules:
- apiGroups:
  - demo.operator.k8s.yfenyuk.io
  resources:
  - memoryadjusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.operator.k8s.yfenyuk.io
  resources:
  - memoryadjusters/status
  verbs:
  - get
