---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.operator.k8s.yfenyuk.io
  resources:
  - memoryadjusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.operator.k8s.yfenyuk.io
  resources:
  - memoryadjusters/finalizers
  verbs:
  - update
- apiGroups:
  - demo.operator.k8s.yfenyuk.io
  resources:
  - memoryadjusters/status
  verbs:
  - get
  - patch
  - update
