apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "argocd-deployment.fullname" . }}
  namespace: argo
  labels:
    {{- include "argocd-deployment.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.destination.namespace | quote }}
