apiVersion: v1
kind: Service
metadata:
  name: golang-demo-service
  namespace: ns1
  annotations:
spec:
  type: LoadBalancer
  selector:
     app: golang-demo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
