---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-quota-operator-k8s-yfenyuk-io-v1alpha1-clientquota
  failurePolicy: Fail
  name: mclientquota-v1alpha1.kb.io
  rules:
  - apiGroups:
    - quota.operator.k8s.yfenyuk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clientquotas
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-quota-operator-k8s-yfenyuk-io-v1alpha1-clientquota
  failurePolicy: Fail
  name: vclientquota-v1alpha1.kb.io
  rules:
  - apiGroups:
    - quota.operator.k8s.yfenyuk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clientquotas
  sideEffects: None
