{{- $files := .Files }}
{{- $path := "secrets-decrypted/credentials.decrypted.yaml"}}
{{- $secretData := $files.Get $path | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-secret
  namespace: medium
type: Opaque
data:
{{- range $name, $secret := ($secretData) }}
  {{ $name }}: {{ $secret | b64enc }}
{{- end }}
---