apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-scanning-filters
  namespace: datree
data:
  skiplist: |
    - argo;(.*);(.*)
    - ingress-nginx;(.*);(.*)
    - kube-public;(.*);(.*)
    - default;(.*);(.*)
    - kube-node-lease;(.*);(.*)
