{{- $files := .Files }}
{{- $path := "secrets-decrypted/keys.decrypted.yaml"}}
{{- $secretData := $files.Get $path | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificate.secretName }}
  namespace: medium
type: kubernetes.io/tls
data:
{{- range $name, $secret := ($secretData) }}
  {{ $name }}: {{ $secret | b64enc }}
{{- end }}
---