
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yurgenwk/demo-server-hb:{{ .Values.app.version | default "latest"}}
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: heartbeat-secret
              key: username        
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: heartbeat-secret
              key: password        
        - name: MQ_URL
          value: amqp://$(USERNAME):$(PASSWORD)@rabbit-mq-rabbitmq:5672/
---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 3000

  type: NodePort