apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-secret
  namespace: medium
type: Opaque
data:
  username:  {{ .Values.secured_username | b64enc | quote }}
  password:  {{ .Values.secured_password | b64enc | quote }}