apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-demo
  template:
    metadata:
      labels:
        app: golang-demo
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/app/main"
    spec:
      containers:
      - name: demo-server-hashing
        image: yurgenwk/demo-server-hashing:v3.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2800Mi
        env:
        - name: GOGC
          value: "off"
        - name: GOMEMLIMIT
          value: "2400MiB"
        securityContext:
          privileged: true
          runAsUser: 0          
