apiVersion: opentelemetry.io/v1alpha1 
kind: Instrumentation 
metadata: 
  name: demo-instrumentation 
spec: 
  exporter: 
    endpoint: http://otelcol-collector:4317
  propagators: 
    - tracecontext 
    - baggage 
  sampler: 
    type: parentbased_traceidratio 
    argument: "1"
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python (same as Go) autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otelcol-collector:4318
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otelcol-collector:4318