---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - quota.operator.k8s.yfenyuk.io
  resources:
  - clientquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quota.operator.k8s.yfenyuk.io
  resources:
  - clientquotas/finalizers
  verbs:
  - update
- apiGroups:
  - quota.operator.k8s.yfenyuk.io
  resources:
  - clientquotas/status
  verbs:
  - get
  - patch
  - update
